#%RAML 1.0 DataType

displayName: Door
properties:
  id:
    type: integer
    required: false
    description: Identifier of the door
  state:
    type: string
    required: false
    description: Current state of the door
    example: open / closed
  keyRequired:
    type: string
    required: false
    description: The key required to open this door
    example: red / blue / yellow / none