#%RAML 1.0 DataType

properties:
  type:
    type: string
    required: true
    example: Barrel
    description: Type of object to spawn
  distance:
    type: integer
    required: true
    example: 300
    description: Distance from player to spawn this object