#%RAML 1.0 NamedExample
value: |
 {
  "id": 0,
                "position": {
                  "x": -32,
                  "y": -240,
                  "z": 24
                },
                "angle": 90,
                "health": 100,
                "type": "Player",
                "typeId": -1,
                "flags": {
                  "MF_SOLID": true,
                  "MF_SHOOTABLE": true
                },
                "colour": "Green: ",
                "armor": 0,
                "kills": 0,
                "items": 0,
                "secrets": 0,
                "weapon": 1,
                "weapons": {
                  "Handgun": true,
                  "Shotgun": false,
                  "Chaingun": false,
                  "Rocket Launcher": true,
                  "Plasma Rifle": false,
                  "BFG": false
                },
                "ammo": {
                  "Bullets": 100,
                  "Shells": 30,
                  "Cells": 0,
                  "Rockets": 0
                },
                "keyCards": {
                  "blue": false,
                  "red": false,
                  "yellow": false
                },
                "cheatFlags": {}
}
