#%RAML 1.0 DataType

displayName: Position
properties:
  x:
    type: integer
    required: false
  y:
    type: integer
    required: false
  z:
    type: integer
    required: false
    description: positive z points upwards