#%RAML 1.0 DataType

displayName: World
properties:
  episode:
    type: integer
    required: false
    description: The current episode 
  map:
    type: integer
    required: false
    description: The current map
  wad:
    type: string
    required: false
    description: The wad file currently in use
  skill:
    type: string
    required: false
    description: The current skill level selected
  lights:
    type: string
    required: false
    description: Whether the lights are "on" or "off"
