#include "api.h"

api_obj_description_t api_descriptors[NUMDESCRIPTIONS] = {
  {-1, "Player"},
  {0, "Unknown?"},
  {1, "Player 1 start"},
  {2, "Player 2 start"},
  {3, "Player 3 start"},
  {4, "Player 4 start"},
  {11, "Deathmatch start positions"},
  {14, "Teleport landing"},
  {3004, "FORMER HUMAN"},
  {84, "WOLFENSTEIN SS"},
  {9, "FORMER HUMAN SERGEANT"},
  {65, "HEAVY WEAPON DUDE"},
  {3001, "IMP"},
  {3002, "DEMON"},
  {58, "SPECTRE"},
  {3006, "LOST SOUL"},
  {3005, "CACODEMON"},
  {69, "HELL KNIGHT"},
  {3003, "BARON OF HELL"},
  {68, "ARACHNOTRON"},
  {71, "PAIN ELEMENTAL"},
  {66, "REVENANT"},
  {67, "MANCUBUS"},
  {64, "ARCH-VILE"},
  {7, "SPIDER MASTERMIND"},
  {16, "CYBER-DEMON"},
  {88, "BOSS BRAIN"},
  {89, "Boss Shooter"},
  {87, "Spawn Spot"},
  {2005, "Chainsaw"},
  {2001, "Shotgun"},
  {82, "Double-barreled shotgun"},
  {2002, "Chaingun"},
  {2003, "Rocket launcher"},
  {2004, "Plasma gun"},
  {2006, "Bfg9000"},
  {2007, "Ammo clip"},
  {2008, "Shotgun shells"},
  {2010, "A rocket"},
  {2047, "Cell charge"},
  {2048, "Box of Ammo"},
  {2049, "Box of Shells"},
  {2046, "Box of Rockets"},
  {17, "Cell charge pack"},
  {8, "Backpack"},
  {2011, "Stimpak"},
  {2012, "Medikit"},
  {2014, "Health Potion +1% health"},
  {2015, "Spirit Armor +1% armor"},
  {2018, "Green armor 100%"},
  {2019, "Blue armor 200%"},
  {83, "Megasphere: 200% health, 200% armor"},
  {2013, "Soulsphere, Supercharge, +100% health"},
  {2022, "Invulnerability"},
  {2023, "Berserk Strength and 100% health"},
  {2024, "Invisibility"},
  {2025, "Radiation suit"},
  {2026, "Computer map"},
  {2045, "Lite Amplification goggles"},
  {5, "Blue keycard"},
  {40, "Blue skullkey"},
  {13, "Red keycard"},
  {38, "Red skullkey"},
  {6, "Yellow keycard"},
  {39, "Yellow skullkey"},
  {2035, "Barrel"},
  {72, "A guest appearance by Billy"},
  {48, "Tall, techno pillar"},
  {30, "Tall green pillar"},
  {32, "Tall red pillar"},
  {31, "Short green pillar"},
  {36, "Short green pillar with beating heart"},
  {33, "Short red pillar"},
  {37, "Short red pillar with skull"},
  {47, "Stalagmite: small brown pointy stump"},
  {43, "Burnt tree: gray tree"},
  {54, "Large brown tree"},
  {2028, "Floor lamp"},
  {85, "Tall techno floor lamp"},
  {86, "Short techno floor lamp"},
  {34, "Candle"},
  {35, "Candelabra"},
  {44, "Tall blue firestick"},
  {45, "Tall green firestick"},
  {46, "Tall red firestick"},
  {55, "Short blue firestick"},
  {56, "Short green firestick"},
  {57, "Short red firestick"},
  {70, "Burning barrel"},
  {41, "Evil Eye: floating eye in symbol, over candle"},
  {42, "Floating Skull"},
  {49, "Hanging victim, twitching"},
  {63, "Hanging victim, twitching"},
  {50, "Hanging victim, arms out"},
  {59, "Hanging victim, arms out"},
  {52, "Hanging pair of legs"},
  {60, "Hanging pair of legs"},
  {51, "Hanging victim, 1-legged"},
  {61, "Hanging victim, 1-legged"},
  {53, "Hanging leg"},
  {62, "Hanging leg"},
  {73, "Hanging victim, guts removed"},
  {74, "Hanging victim, guts and brain removed"},
  {75, "Hanging torso, looking down"},
  {76, "Hanging torso, open skull"},
  {77, "Hanging torso, looking up"},
  {78, "Hanging torso, brain removed"},
  {25, "Impaled human"},
  {26, "Twitching impaled human"},
  {27, "Skull on a pole"},
  {28, "5 skulls shish kebob"},
  {29, "Pile of skulls and candles"},
  {10, "Bloody mess"},
  {12, "Bloody mess"},
  {24, "Pool of blood and flesh"},
  {79, "Pool of blood"},
  {80, "Pool of blood"},
  {81, "Pool of brains"},
  {15, "Dead player"},
  {18, "Dead former human"},
  {19, "Dead former sergeant"},
  {20, "Dead imp"},
  {21, "Dead demon"},
  {22, "Dead cacodemon"},
  {23, "Dead lost soul"}
};